### PR TITLE
Feature/attacker model drop down

### PR DESCRIPTION
**Pull request by shimthal61**
### Summary
- Adds faction, model, and available weapon drop downs for attacking stats

### Changes
- `40kdice/public/atk_unit_lookup.js`: created file that searches through .cat files to faction and model, then looks up available weapons
- `40kdice/public/def_unit_lookup.js`: Added console log for potential investigation
- `40kdice/public/dice.html`: Brings in atk_unit_lookup.js script and added input boxes for attacking stats.
- `README.md`: Removed to-do comments that have been moved to Jira board

### Testing
- Running local server and testing weapon options for different unit types (e.g. single entities, characters, units with multiple models).
- Now works with identified crisis battlesuit options

### CODE REVIEW

**Review by lukaross368 — COMMENTED** [review]
Looks like got a bug with crisis suit types, not displaying the sub-types and therefore cannot lookup weapons 

image

**Comment by lukaross368** [comment]
Also should we be expecting the attack values to be auto-filling yet or is that going to be part of the next change ?

**Comment by shimthal61** [comment]
> Also should we be expecting the attack values to be auto-filling yet or is that going to be part of the next change ?

This branch just focuses on populating the weapon list input box, I'll create a separate branch for autopopulating the weapon attributes

> Looks like got a bug with crisis suit types, not displaying the sub-types and therefore cannot lookup weapons

Ah interesting, I'll look into that

**Comment by lukaross368** [comment]
> > Also should we be expecting the attack values to be auto-filling yet or is that going to be part of the next change ?
> 
> This branch just focuses on populating the weapon list input box, I'll create a separate branch for autopopulating the weapon attributes
> 
> > Looks like got a bug with crisis suit types, not displaying the sub-types and therefore cannot lookup weapons
> 
> Ah interesting, I'll look into that

Okay nice one, thanks for confirming

**Comment by lukaross368** [comment]
> Looks like got a bug with crisis suit types, not displaying the sub-types and therefore cannot lookup weapons
> 
> image

Crisis issue looks to be resolved now, did bring up question for how we going to implement auto-fill weapons but we can discuss  

image

**Review by lukaross368 — APPROVED** [review]
LGTM

**Comment by shimthal61** [comment]
> Crisis issue looks to be resolved now, did bring up question for how we going to implement auto-fill weapons but we can discuss

I think this will be fairly simple to implement, the logic will be very similar to how I autopopulate the defensive stats

**Pull request merged**
